[targets.homework]
help = "build homework release, with tagged sections removed"
copy_files = [
    { src = "Python/", dst = "dist/aoc2025-lab5/StudentID_lab5/Python/", ignore = ["__pycache__",] },
    { src = "Csource/", dst = "dist/aoc2025-lab5/StudentID_lab5/Csource/"},
    { src = "lab/", dst = "dist/aoc2025-lab5/StudentID_lab5/lab/"},
    { src = "testbench/", dst = "dist/aoc2025-lab5/StudentID_lab5/testbench/"},
    { src = "Makefile", dst = "dist/aoc2025-lab5/StudentID_lab5/Makefile"},
    { src = "report.md", dst = "dist/aoc2025-lab5/StudentID_lab5/report.md" },
]
sections = [
    { start = "#! hint>>", end = "#! hint<<", action = "replace", with = "### ! <<<========= Implement here =========>>>" },
    { start = "#! hint string>>", end = "#! hint string<<", action = "replace", with = "f'''### ! <<<========= Implement here =========>>>'''" },
    { start = "#! implement>>", end = "#! implement<<", action = "replace", with = "raise NotImplementedError('You need to imeplement here')" },
]
prologue = "./script/prologue.sh"
epilogue = "./script/epilogue.sh"
